### ISSUE TITLE
Status of Godot 4 compatibility?

### ISSUE THREAD

**Issue by gregkrsak** [teebarjunk/Sooty-Engine#1]
If you have time, could you let us know your plans for Godot 4 compatibility? Thanks!

**Comment by teebarjunk** [comment]
I'm in the process of rewriting it for Godot 4, and am abandoning this version, as I prefer Godot 4.
New version has built in script highlighting, custom BBCode system, and more.
https://github.com/teebarjunk/sooty
https://github.com/teebarjunk/sooty-example
Currently a very unstable alpha, without proper save/load, but I work on it regularly.

**Comment by gregkrsak** [comment]
Thanks!!

**Comment by teebarjunk** [comment]
Are there features you are specifically looking for?
